spring.datasource.url=jdbc:mysql://localhost:3306/restful_booker_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
server.port=8085

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate
# Giữ là 'update' để Hibernate tự khớp các class Java với bảng 'bookings' bạn đã tạo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Thêm dòng này để Hibernate biết cách sinh SQL chuẩn cho MySQL/MariaDB của XAMPP
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Swagger / OpenAPI
springdoc.api-docs.path=/api-docs